### PR TITLE
Signals and shorthands

### LINKED ISSUE #2: Support subscribing to subscriptions
re-frame supports multiple layers of subscriptions and it only recomputes what's necessary. cf https://day8.github.io/re-frame/subscriptions/#why-layer-2-extractors

How difficult do you think this could be to port to re-dash?

### PR DESCRIPTION
**Pull request by valerauko**
Resolves #2 

## Input signals
- [x] explicit function
- [x] implicit app-db
- [x] one pair of `:<- [::sub-name]` sugar
- [x] multiple pairs of sugar

## Computation function
- [x] explicit function
- [x] `:->` sugar (ignores subscription params, only depends on input signals)
  `(fn [db _] (:foo db))` => `:-> :foo`
- [x] `:=>` sugar (flattens the params and removes sub name)
  `(fn [db [_ x y]] (+ x y))` ⇨ `:=> (fn [db x y] (+ x y))`

## Tests
```shell
clj -M:cljd:test compile hti.re-dash-test && flutter test
```

- [x] happy path
- [ ] reset state between each test case (since the tests are read-only and don't alter the state it doesn't really matter)
- [x] actual values from derived subscriptions (can't seem to get the value of a Cell (subscription) in a test case)
- [x] syntax error exceptions

### CODE REVIEW

**Comment by wkok** [comment]
Looking very good so far

**Comment by wkok** [comment]
I'm happy to merge/release this unless you're still finishing off a few things?

**Comment by valerauko** [comment]
@wkok i was hoping https://github.com/Tensegritics/ClojureDart/pull/243 would get merged so i could use use_fixtures :each here, but it's been getting stale.

i'll add tests for the syntax error cases then let's get this merged <3

**Comment by valerauko** [comment]
@wkok I added tests for the error cases. It's good to go~

**Pull request merged**
